force-app/main/default/objects/Case/fields/AssignUser__c.field-meta.xml
<CustomField>
    <fullName>AssignUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>アプリケーション「バウチャー管理」で使用</description>
    <label>対象者</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>CaseAssignUser</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/AssignUserId__c.field-meta.xml
<CustomField>
    <fullName>AssignUserId__c</fullName>
    <description>2021/02/04 ゲストユーザの権限変更に伴う変更対応にて追加</description>
    <label>対象者ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <label>試験</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SalesforceCertificatedList</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/UseOfReferenceProblems__c.field-meta.xml
<CustomField>
    <fullName>UseOfReferenceProblems__c</fullName>
    <defaultValue>false</defaultValue>
    <label>参考問題を利用する</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/WillExam__c.field-meta.xml
<CustomField>
    <fullName>WillExam__c</fullName>
    <label>予定日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/SalesforceCertificatedList.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>アドミニストレーター</fullName>
    </customValue>
    <customValue>
        <fullName>上級アドミニストレーター</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Cloud コンサルタント</fullName>
    </customValue>
    <customValue>
        <fullName>Service Cloud コンサルタント</fullName>
    </customValue>
    <customValue>
        <fullName>Field Service Lightning コンサルタント</fullName>
    </customValue>
    <customValue>
        <fullName>Community Cloud コンサルタント</fullName>
    </customValue>
    <customValue>
        <fullName>Platform アプリケーションビルダー</fullName>
    </customValue>
    <customValue>
        <fullName>Platform デベロッパー</fullName>
    </customValue>
    <customValue>
        <fullName>上級 Platform デベロッパー（1次）</fullName>
    </customValue>
    <customValue>
        <fullName>Einstein Analytics and Discovery コンサルタント</fullName>
    </customValue>
    <customValue>
        <fullName>B2C Commerce デベロッパー</fullName>
    </customValue>
    <customValue>
        <fullName>Pardot スペシャリスト</fullName>
    </customValue>
    <customValue>
        <fullName>Pardot コンサルタント</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud メールスペシャリスト</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud コンサルタント</fullName>
    </customValue>
    <customValue>
        <fullName>CPQ スペシャリスト</fullName>
    </customValue>
    <customValue>
        <fullName>テクニカルアーキテクト</fullName>
    </customValue>
    <customValue>
        <fullName>システムアーキテクト</fullName>
    </customValue>
    <customValue>
        <fullName>アプリケーションアーキテクト</fullName>
    </customValue>
    <customValue>
        <fullName>Data Architecture and Management デザイナー</fullName>
    </customValue>
    <customValue>
        <fullName>Sharing and Visibility デザイナー</fullName>
    </customValue>
    <customValue>
        <fullName>Development Lifecycle and Deployment デザイナー</fullName>
    </customValue>
    <customValue>
        <fullName>Identity and Access Management デザイナー</fullName>
    </customValue>
    <customValue>
        <fullName>Integration Architecture デザイナー</fullName>
    </customValue>
    <customValue>
        <fullName>Heroku Architecture デザイナー</fullName>
    </customValue>
    <customValue>
        <fullName>B2C Commerce Technical Solution デザイナー</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud デベロッパー</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud アドミニストレーター</fullName>
    </customValue>
    <masterLabel>Salesforce認定資格</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CaseController.cls
/**
 * @Contents   : ケースコントローラー
 * @Author     : kakimura
 * @Since      : 2021/01/27
 * @LastUpdate : 2021/02/04
 */
public without sharing class CaseController {
    // Caseレコード登録(LWCより呼び出しされる)
    @AuraEnabled
    public static void insertCaseVoucher(string AssignUserId, string Exam, date WillExam, Boolean useOfReferenceProblems, string Note, string Subject, string Origin){
        system.debug('■■■■■ Log:insertCaseVouche Start');
        case CaseA = new case(  AssignUserId__c = AssignUserId,
                                AssignUser__c = AssignUserId,
                                Exam__c = Exam,
                                WillExam__c = WillExam,
                                useOfReferenceProblems__c = useOfReferenceProblems,
                                Note__c= Note,
                                Subject = Subject,
                                Origin = Origin
                                );
        insert CaseA;
        system.debug('■■■■■ Log:insertCaseVouche End');
        return;
    }
}