force-app/main/default/objects/ExaminationInfo__c/ExaminationInfo__c.object-meta.xml
<CustomObject>
    <label>受験情報</label>
    <nameField>
        <displayFormat>EXAM-{0}</displayFormat>
        <label>受験情報Id</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ExaminationInfo__c/fields/AssignUser__c.field-meta.xml
<CustomField>
    <fullName>AssignUser__c</fullName>
    <formula>Voucher__r.AssignUser__r.LastName &amp; &quot; &quot; &amp;  Voucher__r.AssignUser__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>対象者</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExaminationInfo__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <label>試験</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SalesforceCertificatedList</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ExaminationInfo__c/fields/PassOrFail__c.field-meta.xml
<CustomField>
    <fullName>PassOrFail__c</fullName>
    <label>合否</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PassOrFail</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ExaminationInfo__c/fields/Voucher__c.field-meta.xml
<CustomField>
    <fullName>Voucher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>バウチャー</label>
    <referenceTo>Voucher__c</referenceTo>
    <relationshipLabel>受験情報</relationshipLabel>
    <relationshipName>Examination_Voucher</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ExaminationInfo__c/fields/WillExam__c.field-meta.xml
<CustomField>
    <fullName>WillExam__c</fullName>
    <inlineHelpText>初期登録時には予定日を入力してください。
受験した場合は、受験日を入力してください。
「会社立替費用決定通知書」に必要です。</inlineHelpText>
    <label>受験日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FinalDecision__c/FinalDecision__c.object-meta.xml
<CustomObject>
    <label>決裁</label>
    <nameField>
        <label>決裁番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>バウチャー</label>
    <nameField>
        <label>バウチャー番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/AssignUser__c.field-meta.xml
<CustomField>
    <fullName>AssignUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>対象者</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Voucher_User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <formula>TEXT(Case__r.Exam__c)</formula>
    <label>試験</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/FinalDecision__c.field-meta.xml
<CustomField>
    <fullName>FinalDecision__c</fullName>
    <label>決裁</label>
    <referenceTo>FinalDecision__c</referenceTo>
    <relationshipLabel>バウチャー</relationshipLabel>
    <relationshipName>Voucher_FinalDecision</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/PassOrFail.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>合格</fullName>
    </customValue>
    <customValue>
        <fullName>不合格</fullName>
    </customValue>
    <masterLabel>合否</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SalesforceCertificatedList.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>アドミニストレーター</fullName>
    </customValue>
    <customValue>
        <fullName>上級アドミニストレーター</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Cloud コンサルタント</fullName>
    </customValue>
    <customValue>
        <fullName>Service Cloud コンサルタント</fullName>
    </customValue>
    <customValue>
        <fullName>Field Service Lightning コンサルタント</fullName>
    </customValue>
    <customValue>
        <fullName>Community Cloud コンサルタント</fullName>
    </customValue>
    <customValue>
        <fullName>Platform アプリケーションビルダー</fullName>
    </customValue>
    <customValue>
        <fullName>Platform デベロッパー</fullName>
    </customValue>
    <customValue>
        <fullName>上級 Platform デベロッパー（1次）</fullName>
    </customValue>
    <customValue>
        <fullName>Einstein Analytics and Discovery コンサルタント</fullName>
    </customValue>
    <customValue>
        <fullName>B2C Commerce デベロッパー</fullName>
    </customValue>
    <customValue>
        <fullName>Pardot スペシャリスト</fullName>
    </customValue>
    <customValue>
        <fullName>Pardot コンサルタント</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud メールスペシャリスト</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud コンサルタント</fullName>
    </customValue>
    <customValue>
        <fullName>CPQ スペシャリスト</fullName>
    </customValue>
    <customValue>
        <fullName>テクニカルアーキテクト</fullName>
    </customValue>
    <customValue>
        <fullName>システムアーキテクト</fullName>
    </customValue>
    <customValue>
        <fullName>アプリケーションアーキテクト</fullName>
    </customValue>
    <customValue>
        <fullName>Data Architecture and Management デザイナー</fullName>
    </customValue>
    <customValue>
        <fullName>Sharing and Visibility デザイナー</fullName>
    </customValue>
    <customValue>
        <fullName>Development Lifecycle and Deployment デザイナー</fullName>
    </customValue>
    <customValue>
        <fullName>Identity and Access Management デザイナー</fullName>
    </customValue>
    <customValue>
        <fullName>Integration Architecture デザイナー</fullName>
    </customValue>
    <customValue>
        <fullName>Heroku Architecture デザイナー</fullName>
    </customValue>
    <customValue>
        <fullName>B2C Commerce Technical Solution デザイナー</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud デベロッパー</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud アドミニストレーター</fullName>
    </customValue>
    <masterLabel>Salesforce認定資格</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RegistPassingExaminationController.cls
public without sharing class RegistPassingExaminationController {
    @AuraEnabled(cacheable=true)
    public static List<Object> selectChatterUser(String param){
        String key = '%' + param + '%';
        return [SELECT Id, Name, Email, SmallPhotoUrl FROM User WHERE (Email like :key) AND (IsActive = true)];
    }

    @AuraEnabled(cacheable=true)
    public static List<Object> getRegistVoucherId(String UserId){
        return [SELECT Id FROM Voucher__c WHERE (Name = '資格保有者登録用') AND (AssignUser__c = :UserId) LIMIT 1];
    }

    @AuraEnabled(cacheable=true)
    public static List<Object> getFinalDecisionId(){
        return [SELECT Id FROM FinalDecision__c WHERE Name = '資格保有者登録用' LIMIT 1];
    }
    
    // 2021/02/18 ADD S
    @AuraEnabled
    // バウチャーレコード登録(LWCより呼び出しされる)
    public static String insertVoucher(string AssignUserId, string FinalDecision, string Name){
        system.debug('■■■■■ Log:insertVoucher Start');
        Voucher__c VoucherA = new Voucher__c(
                                    AssignUser__c    = AssignUserId,
                                    FinalDecision__c = FinalDecision,
                                    Name             = Name
                                    );
        insert VoucherA;
        system.debug('■■■■■ Log:insertVoucher End');
        return String.valueOf(VoucherA.Id);
    }
    // 受験情報レコード登録(LWCより呼び出しされる)
    @AuraEnabled
    public static void insertExaminationInfo(string exam, date willExam, string passOrFail, string voucher){
        system.debug('■■■■■ Log:inserttExaminationInfo Start');
        ExaminationInfo__c ExaminationInfoA = new ExaminationInfo__c(
                                    Exam__c = exam,
                                    WillExam__c = willExam,
                                    PassOrFail__c = passOrFail,
                                    voucher__c = voucher
                                    );
        insert ExaminationInfoA;
        system.debug('■■■■■ Log:insertExaminationInfo End');
        return;
    }
    // 2021/02/18 ADD E
}