force-app/main/default/objects/ExaminationInfo__c/ExaminationInfo__c.object-meta.xml
<CustomObject>
    <label>受験情報</label>
    <nameField>
        <displayFormat>EXAM-{0}</displayFormat>
        <label>受験情報Id</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ExaminationInfo__c/fields/Voucher__c.field-meta.xml
<CustomField>
    <fullName>Voucher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>バウチャー</label>
    <referenceTo>Voucher__c</referenceTo>
    <relationshipLabel>受験情報</relationshipLabel>
    <relationshipName>Examination_Voucher</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinalDecision__c/FinalDecision__c.object-meta.xml
<CustomObject>
    <label>決裁</label>
    <nameField>
        <label>決裁番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>バウチャー</label>
    <nameField>
        <label>バウチャー番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/FinalDecision__c.field-meta.xml
<CustomField>
    <fullName>FinalDecision__c</fullName>
    <label>決裁</label>
    <referenceTo>FinalDecision__c</referenceTo>
    <relationshipLabel>バウチャー</relationshipLabel>
    <relationshipName>Voucher_FinalDecision</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestRegistPassingExaminationController.cls
/* @Contents バウチャー管理
 * @Author matsuzaki
 * @Since 2020/10/12
 * @LastUpdate 2020/10/12
 */
@isTest
public with sharing class TestRegistPassingExaminationController {
    @isTest static void TestRegistPassingExaminationController() {
        TestCreateDataUtil CreateDataUtil = new TestCreateDataUtil();

        //テスト開始
        Test.starttest();
        User adminUser = CreateDataUtil.createdUser('CreateExamRecordadmin','admin');
        User standardUser = CreateDataUtil.createdUser('CreateExamRecord', '');
        
        System.runAs(adminUser){
            String recordNameAdmin = '資格保有者登録用';
            List<FinalDecision__c> FinalDecisionList = CreateDataUtil.createFinalDecisionRecord(recordNameAdmin);
            List<Voucher__c> VoucherList = CreateDataUtil.createVoucherRecord(FinalDecisionList[1].id);
            List<ExaminationInfo__c> ExaminationInfoList = CreateDataUtil.createExaminationInfoRecord(VoucherList , standardUser.Id);
        
            RegistPassingExaminationController.selectChatterUser('test@xxx.com');
            RegistPassingExaminationController.getRegistVoucherId(standardUser.Id);
            RegistPassingExaminationController.getFinalDecisionId();

        }
        Test.stoptest();
    }
}