force-app/main/default/objects/ExaminationInfo__c/ExaminationInfo__c.object-meta.xml
<CustomObject>
    <label>受験情報</label>
    <nameField>
        <displayFormat>EXAM-{0}</displayFormat>
        <label>受験情報Id</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ExaminationInfo__c/fields/Voucher__c.field-meta.xml
<CustomField>
    <fullName>Voucher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>バウチャー</label>
    <referenceTo>Voucher__c</referenceTo>
    <relationshipLabel>受験情報</relationshipLabel>
    <relationshipName>Examination_Voucher</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinalDecision__c/FinalDecision__c.object-meta.xml
<CustomObject>
    <label>決裁</label>
    <nameField>
        <label>決裁番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>バウチャー</label>
    <nameField>
        <label>バウチャー番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/FinalDecision__c.field-meta.xml
<CustomField>
    <fullName>FinalDecision__c</fullName>
    <label>決裁</label>
    <referenceTo>FinalDecision__c</referenceTo>
    <relationshipLabel>バウチャー</relationshipLabel>
    <relationshipName>Voucher_FinalDecision</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestExaminationInputController.cls
/* @Contents バウチャー管理
 * @Author matsuzaki
 * @Since 2020/10/12
 * @LastUpdate 2021/02/16
 */
@isTest
public with sharing class TestExaminationInputController {
    @isTest public static void TestgetVoucherList(){
        ExaminationInputController.getVoucherList();
    }
    @isTest static void TestMethod1(){
        // updatetExaminationInfoのテスト
        String recordNameAdmin = '資格保有者登録用';
        TestCreateVoucherDataUtil CreateVoucherDataUtil = new TestCreateVoucherDataUtil();
        // ユーザ作成
        User adminUser    = CreateVoucherDataUtil.createdUser('CreateExamRecordadmin','admin');
        User standardUser = CreateVoucherDataUtil.createdUser('CreateExamRecord', '');
        // 決裁作成
        List<FinalDecision__c> FinalDecisionList = CreateVoucherDataUtil.createFinalDecisionRecord(recordNameAdmin);
        // バウチャー作成
        List<Voucher__c> VoucherList = CreateVoucherDataUtil.createVoucherRecord(FinalDecisionList);
        // 受験情報作成
        List<ExaminationInfo__c> ExaminationInfoList = CreateVoucherDataUtil.createExaminationInfoRecord(VoucherList , standardUser.Id);
        // テスト開始
        Test.starttest();
            System.runAs(adminUser){
                ExaminationInputController.updatetExaminationInfo(
                    String.valueOf(ExaminationInfoList[0].id),
                    'アドミニストレーター',
                    Date.valueOf('2020-02-10'), 
                    '合格');
            }
        Test.stoptest();
    }
}