force-app/main/default/objects/eqAnswer__c/eqAnswer__c.object-meta.xml
<CustomObject>
    <description>2019/10/17
Salesforce認定資格対策用オブジェクト
【解答データ格納用】</description>
    <label>資格試験解答</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>A-No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/eqAnswer__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <description>設問を入力</description>
    <label>選択肢</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/eqAnswer__c/fields/eqQuestion__c.field-meta.xml
<CustomField>
    <fullName>eqQuestion__c</fullName>
    <label>資格試験(参照先)</label>
    <referenceTo>eqQuestion__c</referenceTo>
    <relationshipLabel>資格試験解答一覧</relationshipLabel>
    <relationshipName>Answer2Question</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/eqAnswer__c/fields/isAnswer__c.field-meta.xml
<CustomField>
    <fullName>isAnswer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>正解：True</description>
    <label>正解判定</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/eqQuestion__c/eqQuestion__c.object-meta.xml
<CustomObject>
    <description>2019/10/17
Salesforce認定資格対策用オブジェクト
【問題データ格納用】</description>
    <label>資格試験問題</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Q-No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/eqQuestion__c/fields/Detail__c.field-meta.xml
<CustomField>
    <fullName>Detail__c</fullName>
    <description>試験問題</description>
    <label>設問</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/eqQuestion__c/fields/ExamType__c.field-meta.xml
<CustomField>
    <fullName>ExamType__c</fullName>
    <description>問題に対応する資格試験</description>
    <label>認定資格名</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SalesforceCertificatedList</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/eqQuestion__c/fields/PDF_No__c.field-meta.xml
<CustomField>
    <fullName>PDF_No__c</fullName>
    <description>過去問内に採番されているNo</description>
    <label>PDF No</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ExaminationInfo__c/ExaminationInfo__c.object-meta.xml
<CustomObject>
    <label>受験情報</label>
    <nameField>
        <displayFormat>EXAM-{0}</displayFormat>
        <label>受験情報Id</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ExaminationInfo__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <label>試験</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SalesforceCertificatedList</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ExaminationInfo__c/fields/PassOrFail__c.field-meta.xml
<CustomField>
    <fullName>PassOrFail__c</fullName>
    <label>合否</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PassOrFail</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ExaminationInfo__c/fields/Voucher__c.field-meta.xml
<CustomField>
    <fullName>Voucher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>バウチャー</label>
    <referenceTo>Voucher__c</referenceTo>
    <relationshipLabel>受験情報</relationshipLabel>
    <relationshipName>Examination_Voucher</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinalDecision__c/FinalDecision__c.object-meta.xml
<CustomObject>
    <label>決裁</label>
    <nameField>
        <label>決裁番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinalDecision__c/fields/Headcount__c.field-meta.xml
<CustomField>
    <fullName>Headcount__c</fullName>
    <label>人数</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FinalDecision__c/fields/title__c.field-meta.xml
<CustomField>
    <fullName>title__c</fullName>
    <label>件名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>バウチャー</label>
    <nameField>
        <label>バウチャー番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <formula>TEXT(Case__r.Exam__c)</formula>
    <label>試験</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/FinalDecision__c.field-meta.xml
<CustomField>
    <fullName>FinalDecision__c</fullName>
    <label>決裁</label>
    <referenceTo>FinalDecision__c</referenceTo>
    <relationshipLabel>バウチャー</relationshipLabel>
    <relationshipName>Voucher_FinalDecision</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/PassOrFail.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>合格</fullName>
    </customValue>
    <customValue>
        <fullName>不合格</fullName>
    </customValue>
    <masterLabel>合否</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SalesforceCertificatedList.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>アドミニストレーター</fullName>
    </customValue>
    <customValue>
        <fullName>上級アドミニストレーター</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Cloud コンサルタント</fullName>
    </customValue>
    <customValue>
        <fullName>Service Cloud コンサルタント</fullName>
    </customValue>
    <customValue>
        <fullName>Field Service Lightning コンサルタント</fullName>
    </customValue>
    <customValue>
        <fullName>Community Cloud コンサルタント</fullName>
    </customValue>
    <customValue>
        <fullName>Platform アプリケーションビルダー</fullName>
    </customValue>
    <customValue>
        <fullName>Platform デベロッパー</fullName>
    </customValue>
    <customValue>
        <fullName>上級 Platform デベロッパー（1次）</fullName>
    </customValue>
    <customValue>
        <fullName>Einstein Analytics and Discovery コンサルタント</fullName>
    </customValue>
    <customValue>
        <fullName>B2C Commerce デベロッパー</fullName>
    </customValue>
    <customValue>
        <fullName>Pardot スペシャリスト</fullName>
    </customValue>
    <customValue>
        <fullName>Pardot コンサルタント</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud メールスペシャリスト</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud コンサルタント</fullName>
    </customValue>
    <customValue>
        <fullName>CPQ スペシャリスト</fullName>
    </customValue>
    <customValue>
        <fullName>テクニカルアーキテクト</fullName>
    </customValue>
    <customValue>
        <fullName>システムアーキテクト</fullName>
    </customValue>
    <customValue>
        <fullName>アプリケーションアーキテクト</fullName>
    </customValue>
    <customValue>
        <fullName>Data Architecture and Management デザイナー</fullName>
    </customValue>
    <customValue>
        <fullName>Sharing and Visibility デザイナー</fullName>
    </customValue>
    <customValue>
        <fullName>Development Lifecycle and Deployment デザイナー</fullName>
    </customValue>
    <customValue>
        <fullName>Identity and Access Management デザイナー</fullName>
    </customValue>
    <customValue>
        <fullName>Integration Architecture デザイナー</fullName>
    </customValue>
    <customValue>
        <fullName>Heroku Architecture デザイナー</fullName>
    </customValue>
    <customValue>
        <fullName>B2C Commerce Technical Solution デザイナー</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud デベロッパー</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud アドミニストレーター</fullName>
    </customValue>
    <masterLabel>Salesforce認定資格</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestCreateDataUtil.cls
/* @Contents テストデータ作成共通クラス
 * @Author matsuzaki
 * @Since 2020/10/08
 * @LastUpdate 2020/10/12
 */
public with sharing class TestCreateDataUtil {

    /*
     *@決裁のデータ作成
     *@String name : 決裁番号
     */
    @TestVisible List<FinalDecision__c> createFinalDecisionRecord(String recordName){

        FinalDecision__c FinalDecision = new FinalDecision__c(Name = recordName,
                                                            Title__c = 'テスト',
                                                            Amount__c = 1000000,
                                                            Headcount__c = 20);

        try{
            System.debug('Attempting to insert positions');
            insert FinalDecision;
            System.debug('Insert complete');
        }catch(System.DmlException e){
            System.debug('DML exception:' + e.getDmlMessage(0));
        }

        List<FinalDecision__c> newFinalDecisionList = [select Id, Name, Title__c, Amount__c, Headcount__c from FinalDecision__c];
        return newFinalDecisionList;
    }
    /*
     *@バウチャーのデータ作成
     *@String id : 決裁レコードid
     */
    @TestVisible List<Voucher__c> createVoucherRecord(List<FinalDecision__c> FinalDecisionList){
        List<String> VoucherName = new List<String>();
        VoucherName.add('AAA111111');
        VoucherName.add('BBB222222');
        VoucherName.add('CCC333333');
        VoucherName.add('DDD444444');
        VoucherName.add('資格保有者登録用');

        List<Voucher__c> VoucherList = new List<Voucher__c>();

        for(Integer i = 0 ; i < VoucherName.size() ; i++){
            Voucher__c Voucher = new Voucher__c(Name = VoucherList.get(i),
                                                FinalDecision__c = FinalDecisionList[1].id);
            VoucherList.add(Voucher);
        }

        try{
            System.debug('Attempting to insert positions');
            insert VoucherList;
            System.debug('Insert complete');
        }catch(System.DmlException e){
            System.debug('DML exception:' + e.getDmlMessage(0));
        }

        List<Voucher__c> newVoucherList = [select id, Name from Voucher__c];
        return newVoucherList;

    }

    /*
     *@受験情報のデータ作成
     *@List<Voucher__c> VoucherList : バウチャーレコードのリスト
     *@String UserId : ユーザId
     */
    @TestVisible List<ExaminationInfo__c> createExaminationInfoRecord(List<Voucher__c> VoucherList , String UserId){

        List<ExaminationInfo__c> ExaminationInfoList = new List<ExaminationInfo__c>();

        for(Integer i = 0 ; i < VoucherList.size() ; i++){
            ExaminationInfo__c ExaminationInfo = new ExaminationInfo__c(Exam__c = 'アドミニストレーター',
                                                                        Voucher__c = VoucherList[i].id);
            ExaminationInfoList.add(ExaminationInfo);
        }

        try{
            System.debug('Attempting to insert positions');
            insert ExaminationInfoList;
            System.debug('Insert complete');
        }catch(System.DmlException e){
            System.debug('DML exception:' + e.getDmlMessage(0));
        }

        List<ExaminationInfo__c> newExaminationInfoList = [select id, Name, PassOrFail__c from ExaminationInfo__c];
        return newExaminationInfoList;

    }

    /*
     * @資格試験問題と回答のデータ作成
     */ 
    @TestVisible List<eqQuestion__c> createeqQuestionRecord(){
        List<Integer> PfdNo = new List<Integer>();
        PfdNo.add(1);
        PfdNo.add(2);
        PfdNo.add(3);
        PfdNo.add(4);
        PfdNo.add(5);

        List<String> Detail = new List<String>();
        Detail.add('aaaaaaaaaaaaa');
        Detail.add('bbbbbbbbbbbbb');
        Detail.add('ccccccccccccc');
        Detail.add('ddddddddddddd');
        Detail.add('eeeeeeeeeeeee');

        List<eqQuestion__c> eqQuestionList = new List<eqQuestion__c>();

        for(Integer i = 0 ; i < PfdNo.size() ; i++){
            eqQuestion__c eqQuestion = new eqQuestion__c(PDF_No__c = PfdNo.get(i),
                                                        Detail__c = Detail.get(i),
                                                        ExamType__c = 'アドミニストレーター');
            eqQuestionList.add(eqQuestion);
        }

        try{
            System.debug('Attempting to insert positions');
            insert eqQuestionList;
            System.debug('Insert complete');
        }catch(System.DmlException e){
            System.debug('DML exception:' + e.getDmlMessage(0));
        }

        List<eqQuestion__c> neweqQuestionList = [select id, Name from eqQuestion__c];
        List<eqAnswer__c> eqAnswerList = new List<eqAnswer__c>();

        for(Integer i = 0 ; i < neweqQuestionList.size() ; i++){
            eqAnswer__c eqAnswer = new eqAnswer__c(eqQuestion__c = neweqQuestionList[i].id,
                                                    Answer__c = '正解Death!!',
                                                    isAnswer__c = True);
            eqAnswerList.add(eqAnswer);
        }

        try{
            System.debug('Attempting to insert positions');
            insert eqAnswerList;
            System.debug('Insert complete');
        }catch(System.DmlException e){
            System.debug('DML exception:' + e.getDmlMessage(0));
        }

        return neweqQuestionList;

    }

    /*
     * @テスト用ユーザ作成
     * @String name : ユーザ名
     * @String pName : プロファイル名
     */ 
    @TestVisible User createdUser(String name, String pName){
        Profile profile;
        if(pName == 'admin'){
            profile = getAdminProfile();
        }else{
            profile = getStandardProfile();
        }
        String profileId =profile.id;

        User user = new User();
        user.Email = name + 'test@xxx.com';
        user.UserName = name + 'test@xxx.com';
        user.FirstName = name;
        User.LastName = 'abc';
        user.Alias = user.UserName.split('@')[0].left(8);
        user.profileId = profileId;
        user.EmailEncodingKey = 'ISO-2022-JP';
        user.LanguageLocaleKey = 'ja';
        user.LocaleSidKey = 'ja_JP';
        user.TimeZoneSidKey = 'Asia/Tokyo';

        insert user;

        user = [select Name, UserName, FirstName, LastName, Alias, UserRoleId, ProfileId, CreatedDate from user where UserName = :user.Username limit 1];
        
        return user;
    }

    /*
     * @標準プロファイルのId取得
     */ 
    private static Profile getStandardProfile(){
        List<Profile> profiles = [select Id from Profile where Name = '標準ユーザ' limit 1];
        if (profiles.isEmpty()){
            profiles = [select Id from Profile where Name = 'Standard User' limit 1];
        }
        return profiles[0];
    }

    /*
     *@システム管理者プロファイルのId取得
     */
    private static Profile getAdminProfile(){
        List<Profile> profiles = [select Id from Profile where Name = 'システム管理者' limit 1];
        if (profiles.isEmpty()){
            profiles = [select Id from Profile where Name = 'System Admin' limit 1];
        }
        return profiles[0];
    }

    /*
     *@権限セットをユーザに付与
     */
    @TestVisible void getPermissionSet(User user, String PerSetName){
        PermissionSet PerSet = [select Id from PermissionSet where Name =:PerSetName];
        PermissionSetAssignment PerSetAss = new PermissionSetAssignment(
            AssigneeId = user.Id,
            PermissionSetId = PerSet.Id
        );
        insert PerSetAss;
    }
}