force-app/main/default/objects/eqAnswer__c/eqAnswer__c.object-meta.xml
<CustomObject>
    <description>2019/10/17
Salesforce認定資格対策用オブジェクト
【解答データ格納用】</description>
    <label>資格試験解答</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>A-No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/eqAnswer__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <description>設問を入力</description>
    <label>選択肢</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/eqAnswer__c/fields/eqQuestion__c.field-meta.xml
<CustomField>
    <fullName>eqQuestion__c</fullName>
    <label>資格試験(参照先)</label>
    <referenceTo>eqQuestion__c</referenceTo>
    <relationshipLabel>資格試験解答一覧</relationshipLabel>
    <relationshipName>Answer2Question</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/eqAnswer__c/fields/isAnswer__c.field-meta.xml
<CustomField>
    <fullName>isAnswer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>正解：True</description>
    <label>正解判定</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/eqQuestion__c/eqQuestion__c.object-meta.xml
<CustomObject>
    <description>2019/10/17
Salesforce認定資格対策用オブジェクト
【問題データ格納用】</description>
    <label>資格試験問題</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Q-No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/eqQuestion__c/fields/Detail__c.field-meta.xml
<CustomField>
    <fullName>Detail__c</fullName>
    <description>試験問題</description>
    <label>設問</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/eqQuestion__c/fields/ExamType__c.field-meta.xml
<CustomField>
    <fullName>ExamType__c</fullName>
    <description>問題に対応する資格試験</description>
    <label>認定資格名</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SalesforceCertificatedList</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/SalesforceCertificatedList.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>アドミニストレーター</fullName>
    </customValue>
    <customValue>
        <fullName>上級アドミニストレーター</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Cloud コンサルタント</fullName>
    </customValue>
    <customValue>
        <fullName>Service Cloud コンサルタント</fullName>
    </customValue>
    <customValue>
        <fullName>Field Service Lightning コンサルタント</fullName>
    </customValue>
    <customValue>
        <fullName>Community Cloud コンサルタント</fullName>
    </customValue>
    <customValue>
        <fullName>Platform アプリケーションビルダー</fullName>
    </customValue>
    <customValue>
        <fullName>Platform デベロッパー</fullName>
    </customValue>
    <customValue>
        <fullName>上級 Platform デベロッパー（1次）</fullName>
    </customValue>
    <customValue>
        <fullName>Einstein Analytics and Discovery コンサルタント</fullName>
    </customValue>
    <customValue>
        <fullName>B2C Commerce デベロッパー</fullName>
    </customValue>
    <customValue>
        <fullName>Pardot スペシャリスト</fullName>
    </customValue>
    <customValue>
        <fullName>Pardot コンサルタント</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud メールスペシャリスト</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud コンサルタント</fullName>
    </customValue>
    <customValue>
        <fullName>CPQ スペシャリスト</fullName>
    </customValue>
    <customValue>
        <fullName>テクニカルアーキテクト</fullName>
    </customValue>
    <customValue>
        <fullName>システムアーキテクト</fullName>
    </customValue>
    <customValue>
        <fullName>アプリケーションアーキテクト</fullName>
    </customValue>
    <customValue>
        <fullName>Data Architecture and Management デザイナー</fullName>
    </customValue>
    <customValue>
        <fullName>Sharing and Visibility デザイナー</fullName>
    </customValue>
    <customValue>
        <fullName>Development Lifecycle and Deployment デザイナー</fullName>
    </customValue>
    <customValue>
        <fullName>Identity and Access Management デザイナー</fullName>
    </customValue>
    <customValue>
        <fullName>Integration Architecture デザイナー</fullName>
    </customValue>
    <customValue>
        <fullName>Heroku Architecture デザイナー</fullName>
    </customValue>
    <customValue>
        <fullName>B2C Commerce Technical Solution デザイナー</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud デベロッパー</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud アドミニストレーター</fullName>
    </customValue>
    <masterLabel>Salesforce認定資格</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ExamTestFormatController.cls
public with sharing class ExamTestFormatController {
    @AuraEnabled(cacheable=true)
    public static List<Object> getExistExam() {
        return [SELECT ExamType__c FROM eqQuestion__c GROUP BY ExamType__c];
    }

    @AuraEnabled(cacheable=true)
    public static List<Object> geteqQuestions(String examname) {
        return [SELECT Id, Detail__c, ExamType__c FROM eqQuestion__c WHERE ExamType__c = :examname];
    }

    @AuraEnabled(cacheable=true)
    public static List<Object> geteqAnswers(String Id) {
        return [SELECT Id, Answer__c, isAnswer__c, eqQuestion__c FROM eqAnswer__c WHERE eqQuestion__c = :Id];
    }
}